version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "06:00"
    labels: []
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      time: "06:00"
    labels: []
